disabled_rules:
  - colon
  - comma
  - force_cast
  - control_statement
opt_in_rules:
  - empty_count
excluded: 
  - Carthage
  - Pods
  - Frameworks
  - WaterTracker/Frameworks

line_length:
    error: 250
    warning: 250
    ignores_comments: true
file_length:
    warning: 800
cyclomatic_complexity:
    warning: 25
function_body_length:
    error: 150
function_parameter_count:
    warning: 7
cyclomatic_complexity:
    error: 30
large_tuple:
    warning: 5

#warning_threshold: 15

identifier_name:
    allowed_symbols: "_"
